# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: items
      PGPORT: 5432
      # Hostname of our Postgres container
      PGHOST: postgres
      DATABASE_URL: ecto://postgres:postgres@db:5432/items
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:12.7
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data1
  # Our Phoenix container
  
  
# Define the volumes
volumes:
  pgdata: